//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Column : NamedElement, IPropertable
{
	public virtual object Type
	{
		get;
		set;
	}

	public virtual object Value
	{
		get;
		set;
	}

	public virtual int ColumnId
	{
		get;
		set;
	}

    public ICollection<Property> properties
    {
        get
        {
            throw new NotImplementedException();
        }

        set
        {
            throw new NotImplementedException();
        }
    }
}

