//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Graph : NamedElement, IPropertable
{
	public virtual object type
	{
		get;
		set;
	}

	public virtual int GraphId
	{
		get;
		set;
	}

    public ICollection<Property> properties
    {
        get; set;
    }
}

