//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Organization : NamedElement, IPropertable, ICkanBuilder, IEntity
{
	public virtual ICollection<Property> properties
	{
		get;
		set;
	}

	public virtual int OrganizationId
	{
		get;
		set;
	}

	public virtual ICollection<User> users
	{
		get;
		set;
	}

	public virtual ICollection<DataSet> DataSet
	{
		get;
		set;
	}

}

