//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Package : NamedElement, ICkanBuilder, IEntity
{
	public virtual IEnumerable<Property> Properties
	{
		get;
		set;
	}

	public virtual IEnumerable<DataSet> DataSets
	{
		get;
		set;
	}

}

