//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Record : NamedElement, IEntity
{
	public virtual object value
	{
		get;
		set;
	}

	public virtual Field Field
	{
		get;
		set;
	}

}

