//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Root : ICkanBuilder, IEntity
{
	public virtual IEnumerable<Visualization> visualizations
	{
		get;
		set;
	}

	public virtual IEnumerable<Graph> graphs
	{
		get;
		set;
	}

	public virtual IEnumerable<Source> Source
	{
		get;
		set;
	}

}

