//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Source : NamedElement, ICkanBuilder, IEntity
{
	public virtual IEnumerable<Group> groups
	{
		get;
		set;
	}

	public virtual IEnumerable<Organization> organizations
	{
		get;
		set;
	}

	public virtual IEnumerable<Tag> tags
	{
		get;
		set;
	}

	public virtual IEnumerable<Package> packages
	{
		get;
		set;
	}

}

